#!/bin/bash

# Skripta generira podatke za 6. zadatak iz druge laboratorijske vježbe
# Osnova korištenja operacijskog sustava Linux.
# OPREZ: skripta generira podatke u trenutnom direktoriju, pazi gdje ćeš
# ju pokrenuti!
#
#   Za sva pitanja, prijedloge i dileme oko ovog zadatka osjećajte se slobodno
#   slati mail na okosl@kset.org
#
#   S ljubavlju napisao,
#   Darko Janeković, 17.12.2018

touch "downloads/SZU_Pitanja_s_odgovorima_2012-13.doc"
touch "downloads/SEM_Upute_za_pisanje_seminara.doc"
touch "downloads/DIGLOG_Digital_Schematics.zip.1"
touch "downloads/RIS_Ljetni_ispitni_rok_(dio_1)_2011-12.jpg"
touch "downloads/RAZNO_Razredbeni_ispit.zip"
touch "downloads/OPP_Kontrolne_zadace_i_auditorne_sa_FER1.rar"
touch "downloads/UTR_3._blic_-_Pitanja_s_prethodnih_godina_2008-09.doc"
touch "downloads/SEM_Sigma-delta_AD_pretvornici.pdf"
touch "downloads/OPEIST_Ispiti_s_FER1.rar"
touch "downloads/UI_Multivariate_Statistical_Analysis,_A_Conceptual_Introduction.pdf"
touch "downloads/SBP_2._Vjezba_-_Optimizacija_2014-15.pdf"
touch "downloads/GEEU_Zavrsni__-_Teorija_2009-10.doc"
touch "downloads/OE_Tutorial_-_Norton,_Thevenin.rar"
touch "downloads/ASP_Dinamicke_matrice_vs_staticke_matrice.c"
touch "downloads/RIP_Skripta_za_ponavljanje_-_za_ZI_2015-16.pdf"
touch "downloads/OPP_SMV_viewer.rar"
touch "downloads/NUMMAT_Zadaci_za_vjezbu_01-05_-_Rjesenja_2011-12.pdf"
touch "downloads/VJEKOM_1._MI_-_Sazetak_2010-11.docx"
touch "downloads/FIZ2_Zadaci_s_FERweba_2013-14.rar"
touch "downloads/OOR_Predavanje_08_2009-10.pdf"
touch "downloads/MUI_Organiziranje_pustolovne_utrke_na_Sljemenu.doc"
touch "downloads/ARH2_3._blic_sa_predavanja_2008-09.doc"
touch "downloads/OSUK_OSK_6LAB_BLIC_2016-2017_2016-17.pdf"
touch "downloads/OKS_3._labos_-_Izvjestaj_-_Slike_2010-11.rar"
touch "downloads/ELE_1._DZ_-_Zadatak_26_2011-12.docx"
touch "downloads/MAT1_Dodatni_zadaci_za_vjezbu_2007-08.rar"
touch "downloads/UUUZ_ZI_2013_-_pitanja_i_odgovori_2012-13.docx"
touch "downloads/NMBP_Zavrsni_2013-14.pdf"
touch "downloads/ELEPOS_Usmeni_-_Odgovori_na_pitanja_(v1)_2008-09.pdf"
touch "downloads/MAT2_Matematika_2_meduispit_gradivo_sumirano_(Ljubo)_2015-16.pdf"
touch "downloads/ARH2_Von_Neumanov_model_racunala_-_Rijeseni_zadaci.rar"
touch "downloads/UTR_SSP_-_Zadatak_3017_2009-10.rar"
touch "downloads/FIZ2_Domaca_zadaca_1,_prof._V._Borjanovic_(7._studenog_2014.)_2014-15.pdf"
touch "downloads/RAZNO_Tjelesna_i_zdravstvena_kultura_(info).doc"
touch "downloads/SiS_Predavanja_-_3._ciklus_2009-10.7z"
touch "downloads/NMI_Samoprovjere_2008-09.rar"
touch "downloads/IRT_IRT_1._labos_2013-14.rar"
touch "downloads/ENEP_Auditorne_-_3._ciklus_(1)_2010-11.pdf"
touch "downloads/ViS_Tutorial_za_zadatke_s_X,Y_i_Z_2010-11.pdf"
touch "downloads/BKM_Introduction_to_local_area_networks.pdf"
touch "downloads/OEMI_3._DZ_2009-10.pdf"
touch "downloads/SPUS_ZI-2015-2016_2015-16.zip"
touch "downloads/TEOMJE_Usmeni_2011-12.docx"
touch "downloads/DOKUMENTI_Raspored_ispita_-_zimski_semestar_2009-10.mht"
touch "downloads/BAZEPOD_Ljetni_ispitni_rok_2016-17.pdf"
touch "downloads/IPOUZ_Predavanja_koja_ulaze_u_blic_2012-13.pdf"
touch "downloads/ELEMEH_EleMeh07_poopceni_kapacitet.pdf"
touch "downloads/DIS_Power_System_Stability_and_Control.pdf"
touch "downloads/DIGLOG_1._MI_-_Grupa_A_2006-07.doc"
touch "downloads/PiPI_Upute_za_Mingw_i_GCC.pdf"
touch "downloads/OS_Ispiti_s_FER1.zip"
touch "downloads/KOMPRO_Usmeni_-_Jezic_-_Sazetak_2011-12.pdf"
touch "downloads/OE_Izvanredna_provjera_znanja_(2011-09-05)_2011-12.zip"
touch "downloads/SKRJ_2._MI_-_Pitanja_za_vjezbu_(v1)_2008-09.doc"
touch "downloads/ASP_Sluzbeni_podsjetnik.pdf.1"
touch "downloads/OE_2._meduispit_-_Rjesenja_2010-11.pdf"
touch "downloads/SEM_Koncertna_akustika.doc"
touch "downloads/OPJ_Predavanje_00_i_01_2012-13.zip"
touch "downloads/INFOMRE_Predavanja_i_zadaci_2011-12.zip"
touch "downloads/DIS_Englesko-hrvatski_rjecnik_strucnih_pojmova.doc"
touch "downloads/MATLAB_Ponovljeni_zavrsni_-_rjesenja_2008-09.pdf"
touch "downloads/AIP_3._MI_-_Rjesenja_2008-09.pdf"
touch "downloads/DOS_Discrete_Time_Signal_Processing_(1999).pdf"
touch "downloads/ASP_3._laboratorijska_vjezba_-_objasnjenja_2016-17.zip"
touch "downloads/NOS_1._MI_2015-16.zip"
touch "downloads/ARH1_Kontrolne_zadace_i_pismeni_ispiti_sa_FER1.rar"
touch "downloads/PARPRO_Zavrsni_2016-17.txt"
touch "downloads/MAT3R_Maja_Cvitkovic_-_Kombinatorika_(1994).rar"
touch "downloads/RASUZO_Predavanje_02_2008-09.pdf"
touch "downloads/KOEE_1._DZ_(1)_2009-10.pdf"
touch "downloads/VMK_Labos_profila_2015-16.pdf"
touch "downloads/AUPR_2._labos-_Matlab_2014-15.rar"
touch "downloads/MLI_Konzultacije_(2011-01-05)_2010-11.zip"
touch "downloads/PRIZVU_Meduispit_2014-15.zip"
touch "downloads/KOMSUS_Predavanja_2007-08.rar"
touch "downloads/PiPI_1._mass_instrukcije_(2010-10-06)_2010-11.pdf"
touch "downloads/OI_6._DZ_2011-12.zip"
touch "downloads/OOBL_1._domaca_zadaca_2016-17.7z"
touch "downloads/EMP_izlazni_ispit_-_2013-2014_2013-14.pdf"
touch "downloads/ESA_Labosi_-_Skripta_-_vjezbe_01-03_2007-08.zip"
touch "downloads/KOMAN_KOMPL_rok_24.02.2016_2015-16.pdf"
touch "downloads/NMBP_Ljetni_rok_2015-16_-_sluzbena_rjesenja_2015-16.docx"
touch "downloads/DRES_auditorne_3dio_2012-13.pdf"
touch "downloads/SUI_Usmeni_-_odgovori_na_neka_pitanja.docx"
touch "downloads/DRES_Jesenski_ispitni_rok_2011-12.zip"
touch "downloads/EMP_Zadaci_za_vjezbu_-_Elektrostatika_(1-3)_-_Zadaci_01-26_2009-10.pdf"
touch "downloads/ELE1_Tutorial_-_Pojacala_2010-11.docx"
touch "downloads/ELEINS_2._auditorne_vjezbe_2012-13.pdf"
touch "downloads/FOURIER_An_Introduction_to_Wavelet_Analysis,_D._F._Walnut,_2001.pdf"
touch "downloads/ELE1_ELE1_ISPITI_2007-2013.zip"
touch "downloads/DOKUMENTI_Skripta_za_brucose_FER-a_(v1.2).pdf.1"
touch "downloads/ACAD_1._labos_-_Zadatak_01_2010-11.dwg"
touch "downloads/ENETEH_HE_-_zadatak_s_instaliranim_protokom.doc"
touch "downloads/ELE2_3._labos_-_Graf_za_zadatak_6b_2009-10.pdf"
touch "downloads/MAS_Multimedijske_tehnologije_-_Predavanja_2007-08.rar"
touch "downloads/ENETEH_Teorijska_pitanja_za_MI.docx"
touch "downloads/FIZ2_Zimski_ispitni_rok_2015-16.pdf"
touch "downloads/PROJEKT_A_review_of_SOI_transistor_models.pdf"
touch "downloads/FIZ2_Timoshenko_-_Theory_of_Elasticity.rar"
touch "downloads/OS_MI_-_2006-07__2007-08.rar"
touch "downloads/PARPRO_Predavanja_2._ciklus_2014-15.pdf"
touch "downloads/UUM_Auditorne_ZI_(2012.-13.)_2012-13.zip"
touch "downloads/PRAUT_Simulink_dio_seminara_2014-15.zip"
touch "downloads/OS_Operacijski_sustavi_-_sluzbena_literatura.zip"
touch "downloads/RZNU_Labosi_-_Python_-_Flask_2015-16.zip"
touch "downloads/EMP_Integrali_koji_se_cesto_pojavljuju.docx"
touch "downloads/FIZ1_3._DZ_2008-09.pdf"
touch "downloads/DRS_Zavrsni_-_Pitanja_i_odgovori_2009-10.pdf"
touch "downloads/MPPR_2._MI_-_Rjesenja_2008-09.pdf"
touch "downloads/OSNMEH_OM_-_Zavrsni_Ispit_2012-2013_2012-13.pdf.1"
touch "downloads/UKA_Seminar_-_Tema_17_(2)_2009-10.pdf"
touch "downloads/RAZNO_Rezultati_razredbenog_ispita_-_2006.rar"
touch "downloads/PUE_Konstruktion_Elektrischer_Maschinen_(Wiedemann,_Kellenberger).rar.1"
touch "downloads/ELEKRU_ZIR_2015.-16._2015-16.pdf"
touch "downloads/EEP_2._DZ_2009-10.rar"
touch "downloads/DIGLOG_Zavrsni_14-15_rjesenja_i_postupci_by_Soapy_2014-15.pdf"
touch "downloads/PiPI_Zavrsni_-_Rjesenja_2008-09.rar"
touch "downloads/ARH1_FRISC_i_ARM_-_protocna_struktura.pptx.1"
touch "downloads/UCIELE_1._MI_-_Formule_2011-12.zip"
touch "downloads/IPOUZ_Sva_pitanja_2015-16.pdf"
touch "downloads/KOMMRE_1_blic_-_2013-2014_2013-14.rar"
touch "downloads/TEOEST_TE_LJIR_rjesenja_2016_2015-16.pdf"
touch "downloads/LINALG_1._MI_-_ispit_+_rjesenja_2012-13.rar"
touch "downloads/AEP_2._DZ_(10)_2009-10.zip"
touch "downloads/ACAD_1._labos_-_Zadatak_06_2008-09.pdf"
touch "downloads/ViS_DZ_2009-10.zip"
touch "downloads/JAVA_Neki_materijali_za_prijemni_ispit_iz_OPJJ.zip"
touch "downloads/ViS_2._predmeduispit_2009-10.pdf"
touch "downloads/PiPI_Zadaci_za_vjezbu_s_PMF-a_-_C++_2008-09.zip"
touch "downloads/NOS_AES_-_vodic_i_implementacija_(v1.1)_2011-12.pdf"
touch "downloads/MAT3E_Pripremni_meduispit_2_2011-12.pdf"
touch "downloads/ARH1_Zbirka_zadataka_-_FRISC.pdf"
touch "downloads/ELE1_Mass_instrukcije_-_prof._Baric_-_1._MI_2009-10.rar"
touch "downloads/FIZ1_Problems_in_general_physics_(rjesenja,_2._io).djvu"
touch "downloads/ELEINS_3._Auditorne_2012-13.rar"
touch "downloads/AUPR_6._laboratorijska_vjezba_2014.-2015._2014-15.zip"
touch "downloads/ELERAS_Sazetak_-_1._ciklus_2010-11.docx"
touch "downloads/ELE2_2Lab-izlazni-teorija_2014-15.rar"
touch "downloads/AVSP_MI_1516.pdf"
touch "downloads/ASP_Lab._projekt_A_14-15_2014-15.zip"
touch "downloads/MP_1._labos_-_Rjesenje_2009-10.rar"
touch "downloads/PDS_PDS_2_predavanje.pdf"
touch "downloads/KOMMRE_Blicevi_s_labosa_2012-13.rar"
touch "downloads/FIZ2_Izvodi_-_3._ciklus_2010-11.doc"
touch "downloads/EMP_ZI_2010-2011_2012-13.pdf"
touch "downloads/ELEPOS_Zavrsni_2008-09.pdf"
touch "downloads/DISMAT_1._kolokvij_sa_PMF-a_(2008-05-02).pdf"
touch "downloads/ELEKRU_Zimski_ispitni_rok_2011-2012_2011-12.pdf"
touch "downloads/URS_1._i_2._zadatak-3._ciklus_lab_vjezbi_2015-16.rar"
touch "downloads/NMI_V._Srb_-_Elektrotehnicka_regulativa_i_utjecaj_okoline_(1._dio_knjige).rar"
touch "downloads/TP_Predavanja_-_2._ciklus_2010-11.zip"
touch "downloads/FIZ2_Rijeseni_zadatci_iz_Fizike_2_(prosinac_2015.).pdf"
touch "downloads/DOKUMENTI_Zavrsni_upitnik_kolegija_-_Rezultati_predmeta_prvog_semestra.pdf"
touch "downloads/ELEKRU_(2)Naglic-Osnovi_Teorije_Mreza-Elementi_Elektrickih_Mreza.pdf"
touch "downloads/BRIDZ_Elezovic_-_Upute_za_tecaj_bridza_(2005).doc"
touch "downloads/NUMMAT_MI_i_ZI_2016_2015-16.rar"
touch "downloads/NUKINZ_Meduispit_-_Rjesenja_4._i_6._zadatka_2010-11.rar"
touch "downloads/EMP_ZI_2012.-2013._2012-13.rar.1"
touch "downloads/FIZ1_Zadatci_koje_treba_proci_i_rijesiti_u_Kulisicu_(jako_korisno).docx"
touch "downloads/DOKUMENTI_Popis_akademskih_naziva_i_akademskih_stupnjeva_te_njihovih_kratica.pdf.pdf"
touch "downloads/POSINT_NorthWind_baza_podataka_2009-10.zip"
touch "downloads/FMOS_3._domaca_zadaca_2014-15.zip"
touch "downloads/ELEKOM_Sazetak_predavanja_2011-12.pdf"
touch "downloads/OOPJ_Rijesenja_pokaznog_ZI_2017_2016-17.zip"
touch "downloads/OPJ_Festival_-_instalacija_2012-13.ppt"
touch "downloads/AUPR_Numericki_primjeri_10_-_Rjesenja.pdf"
touch "downloads/JAVA_Zadaci_s_predavanja_04_2015-16.zip"
touch "downloads/TVN_1._DZ_2011-12.docx"
touch "downloads/MIKKOM_Semiconductor_Device_Physics_and_Design.pdf"
touch "downloads/ELESUS_Skripta_za_1.labos_2016-17.txt"
touch "downloads/UPRPOD_Skocir,_Matasic,_Vrdoljak_-_Organizacija_obrade_podataka_(2007).pdf"
touch "downloads/UKA_Skripta_pitanja_za_MI_i_ZI_2013-14.docx"
touch "downloads/SSUS_ELECTRIC_MACHINERY_FUNDAMENTALS.rar"
touch "downloads/UTR_SSP_-_Zadatak_3034_2009-10.rar"
touch "downloads/TEST_D-C_and_A-C_machines_based_on_fundamentals_laws_II.rar.1"
touch "downloads/KEU_Izvori_s_prekidajucim_napajanjem.pdf"
touch "downloads/PRIZVU_Rjesenja_zavrsnog_ispita_2011-12.rar.1"
touch "downloads/OE_Pavic,_Felja_-_Rjesenja_zbirke_zadataka_2007-08.rar"
touch "downloads/OPP_Samoprovjera_znanja_2.ciklusa_2014-15.pdf"
touch "downloads/ARH2_Arh2_ULTIMATE_PACK.zip"
touch "downloads/FIZ1_13._predavanje_(Narancic)_2013-14.zip"
touch "downloads/MAT2_Podsjetnik_-_Domene_funkcija_2007-08.rar"
touch "downloads/PPJ_Zavrsni_2012-13.pdf"
touch "downloads/PRIZVU_Rjesenja_jesenskog_roka_2011-12.rar"
touch "downloads/ESA_Kontrolne_zadace_i_pismeni_sa_FER1.rar"
touch "downloads/ELE1_2._poglavlje_-_Formule_i_pojmovi.rar"
touch "downloads/TP_Zavrsni_-_Grupa_B_2011-12.rar"
touch "downloads/EMP_1._izlazni_ispit_2011-12.doc"
touch "downloads/EUR_Zavrsni_-_Web_prezentacija_2011-12.zip"
touch "downloads/DRES_Skup_materijala_-_1._i_2._ciklus_2009-10.rar"
touch "downloads/RADSUS_1._MI_-_Zadaci_za_vjezbu_2008-09.rar"
touch "downloads/MAT1_Rjesenja_MI_2012.2013_2012-13.pdf"
touch "downloads/MAT3R_Postupci_rjesavanja_za_1._KPZ.rar"
touch "downloads/MIKEL_1._MI_2012-13.pdf"
touch "downloads/Fugazi - 13 Songs.jpg"
touch "downloads/Blue Leaves.mp3"
touch "downloads/07 strangelight.mp3"
touch "downloads/TBF - MAXON Universal - 2004.jpg"
touch "downloads/De Facto - 120E7 (original version).mp3"
touch "downloads/12-song #1.mp3"
touch "downloads/Fugazi - Furniture+2.jpg"
touch "downloads/fugazi - end hits(07) - closed captioned.mp3"
touch "downloads/03 - drag.mp3"
touch "downloads/The Sun Is Going Down II.mp3"
touch "downloads/f59522ynq68.jpg"
touch "downloads/05 - rend it.mp3"
touch "downloads/09 version.mp3"
touch "downloads/02 madagascar.mp3"
touch "downloads/fugazi - end hits(01) - break.mp3"
touch "downloads/fugazi - end hits(05) - five corporations.mp3"
touch "downloads/f13174qro6c.jpg"
touch "downloads/Fugazi - 3 Songs.jpg"
touch "downloads/04 burning.mp3"
touch "downloads/De Facto - Muerte Inoxia.mp3"
touch "downloads/11 Nobody's Listening.mp3"
touch "downloads/defacto - 03 - el professor contra de facto.mp3"
touch "downloads/06 combination lock.mp3"
touch "downloads/11 back to base.mp3"
touch "downloads/Smashed Birds.mp3"
touch "downloads/Fugazi - the argument.jpg"
touch "downloads/14 break in.mp3"
touch "downloads/De Facto - Exit Template.mp3"
touch "downloads/12 downed city.mp3"
touch "downloads/Computational-Electrodynamics-The-Finite-Difference-Time-Domain-Method-Third-Edition.pdf"
touch "downloads/Computational Partial Differential Equations Using MATLAB.pdf"
touch "downloads/Electromagnetic-Modeling-by-Finite-Element-Methods.pdf"
touch "downloads/FEM-msm1333-Chap12-Preliminary-Raleigh-Ritz-method.pdf"
touch "downloads/Finite-element-method.pdf"
touch "downloads/FiniteElementMethod.pdf"
touch "downloads/Functions-Spaces-and-Expansions-Mathematical-Tools-in-Physics-and-Engineering.pdf"
touch "downloads/ha1990.pdf"
touch "downloads/Introduction-to-Finite-Element-Method.pdf"
touch "downloads/Introduction-to-the-finite-element-method-in-electromagnetics.pdf"
touch "downloads/Introduction to the Finite Element Method.pdf"
touch "downloads/Parallel-programming-with-MPI.pdf"
touch "downloads/Partial-differential-equations-an-introduction.pdf"
touch "downloads/S0025-5718-01-01406-5.pdf"
touch "downloads/The-Finite-Element-Method-A-Practical-Course.pdf"
touch "downloads/The-finite-element-method-its-basis-and-fundamentals.pdf"
touch "downloads/The-Mathematical-Theory-of-Finite-Element-Methods.pdf"
touch "downloads/tsuji2012.pdf"
touch "downloads/Scientific Computing with Python 3 - 2nd Revised Edition (2016).epub"
touch "downloads/Scientific Computing with Python 3 - 2nd Revised Edition (2016).pdf"
